### PR TITLE
add colors to console output

### PR DESCRIPTION
**Pull request by ChrisCoffey**
This adds green/red coloring to log output (where supported), making visual test inspection much simpler.

### CODE REVIEW

**Comment by xuwei-k** [comment]
-1

https://github.com/sbt/test-interface/blob/v1.0/src/main/java/org/scalatools/testing/Logger.java#L8

should respect `Logger#ansiCodesSupported`

**Comment by ChrisCoffey** [comment]
Good call, I'll clean that up.

**Comment by rickynils** [comment]
Thanks!

**Comment by rickynils** [comment]
I'll merge it when I get back to a computer...

**Pull request merged**
