### PR TITLE
MiMa setting for Scalajs milestones

### PR DESCRIPTION
**Pull request by ashawley**
A cherry-picked version of #475 to master branch.

### CODE REVIEW

**Comment by non** [comment]
👍

**Comment by non** [comment]
One question about all of this: most projects explicitly set a scala JS version in `project/plugins.sbt` which is used in all cases. I noticed ScalaCheck seems to have a set up where particular users can change the version with an environment variable.

Is this desirable? Maybe I'm out of touch with modern ScalaJS practices but it seems to me like it would be better to make the build/release process _more_ standardized rather than requiring extra environment variables to be set.

(I'm planning to merge this either way, I'm just going to be refactoring the build to make it possible for me to do a ScalaCheck release and I want to figure out if this environment variable stuff is something I can tear out or not.)

**Comment by ashawley** [comment]
Yeah, I agree it's clunky, but I'm not aware of another way.

**Comment by non** [comment]
I'm going to merge this as-is (but it might end up getting changed when I refactor the build).

Thanks!

**Pull request merged**
