### PR TITLE
Fix shrinking of failed test cases in Commands

### LINKED ISSUE #447: Commands sequence shrinking not working (since scala 2.12 update)
I have been investigating the way command failures are reported because it seemed to me that shrinking was not working. I may have spotted a bug introduced with scala 2.12. Here is how to reproduce the behavior I observed:

Apply this diff to be able to see the failure:
```diff
diff --git a/jvm/src/test/scala/org/scalacheck/commands/CommandsSpecification.scala b/jvm/src/test/scala/org/scalacheck/commands/CommandsSpecification.scala
index c60e276..7e66cb1 100644
--- a/jvm/src/test/scala/org/scalacheck/commands/CommandsSpecification.scala
+++ b/jvm/src/test/scala/org/scalacheck/commands/CommandsSpecification.scala
@@ -13,13 +13,13 @@ import org.scalacheck._

 object CommandsSpecification extends Properties("Commands") {

-  property("commands") = TestCommands.property(threadCount = 4)
+  property("commands") = TestCommands.property(threadCount = 1)

   object TestCommands extends Commands {
     case class Counter(var n: Int) {
       val lock = new java.util.concurrent.locks.ReentrantLock
       def inc = { lock.lock; n += 1; lock.unlock; n }
-      def dec = { lock.lock; n -= 1; lock.unlock; n }
+      def dec = { lock.lock; if(n < 90) n -= 1; lock.unlock; n }
       //def inc = { n += 1; n }
       //def dec = { n -= 1; n }
       def get = n
```
In sbt run the following commands and notice the reported `seqcmds`:

#### scala 2.12.6
```
scalacheck >> ++ 2.12.6 jvm/testOnly org.scalacheck.commands.CommandsSpecification
[info] Setting Scala version to 2.12.6 on 3 projects.
[info] Excluded 1 projects, run ++ 2.12.6 -v for more details.
[info] Reapplying settings...
[info] Set current project to scalacheck (in build file:/C:/Users/dalexandre/dev/scalacheck/)
[info] ! Commands.commands: Falsified after 8 passed tests.
[info] > Labels of failing property:
[info] initialstate = 93
[info] seqcmds = (Inc => 94; Get => 94; Inc => 95; Inc => 96; Inc => 97; Inc => 98; Dec => 98; Inc => 99)
[info] > ARG_0: Actions(93,List(Inc, Get, Inc, Inc, Inc, Inc, Dec, Inc),List())
[info] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         org.scalacheck.commands.CommandsSpecification
[error] (jvm / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 0 s, completed 2 janv. 2019 15:57:52
```
#### scala 2.11.12
```
scalacheck >> ++ 2.11.12 jvm/testOnly org.scalacheck.commands.CommandsSpecification
[info] Setting Scala version to 2.11.12 on 4 projects.
[info] Reapplying settings...
[info] Set current project to scalacheck (in build file:/C:/Users/dalexandre/dev/scalacheck/)
[info] ! Commands.commands: Falsified after 3 passed tests.
[info] > Labels of failing property:
[info] initialstate = 99
[info] seqcmds = (Dec => 99)
[info] > ARG_0: Actions(99,List(Dec),List())
[info] > ARG_0_ORIGINAL: Actions(99,List(Inc, Dec, Inc),List())
[info] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         org.scalacheck.commands.CommandsSpecification
[error] (jvm / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 0 s, completed 2 janv. 2019 16:01:28
```
In 2.11.x sequence has been shrunk to one command whereas in 2.12.x the sequence is left untouched. This may be related to #426 concerns as well.

### PR DESCRIPTION
**Pull request by nrinaudo**
This should fix #447.

Remaining questions:
* why does this fix the issue?!
* if I wanted to write a test for this, how would I go about it?

### CODE REVIEW

**Comment by joroKr21** [comment]
Did you try adding a type annotation to the value? Implicits should always have it because otherwise weird things like this could happen.

**Comment by nrinaudo** [comment]
Oh wow I did not even realize it didn’t have one- my projects are set up to not compile when that happens, it’s kind of a blind spot for me now. I’ll fix that, thanks!

**Comment by nrinaudo** [comment]
@joroKr21 well spotted, that's a much more satisfying fix.

Might I suggest adding wartremover, or any other linting tool that fails builds when implicits are not type annotated?

**Comment by ashawley** [comment]
I tried it locally and the failure shrinks now on 2.12.  Thanks for tracking this down!

The ability to test shrinking failures is a missing feature.  This looks good to merge to me.

**Comment by ashawley** [comment]
I noticed the author field on your commit doesn't match your GitHub account.  You can amend your commit with:

```
$ git config --local user.email <EMAIL>
$ git commit --amend --reset-author
```

**Comment by nrinaudo** [comment]
Apologies - my default email is the work one and I tend to forget to change it. This should be ok now.

**Comment by JD557** [comment]
Any updates on this? Is anything blocking this PR?

It would be really helpful to make sure that this makes it into 1.14.1, since otherwise using `Commands` in scala 2.12 is a real pain, since (AFAIK) there's no easy way to find out what command failed the post condition.

**Comment by ashawley** [comment]
An issue about releasing 1.14.1 was opened as #453.

Please add your questions, comments and thumbs up about the release there.

**Pull request merged**
