### PR TITLE
Scala 2.12.0-RC2

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by non** [comment]
👍

**Comment by xuwei-k** [comment]
@rickynils Could you release against Scala 2.12.0-RC2?

**Comment by adriaanm** [comment]
❤️

**Comment by rickynils** [comment]
@xuwei-k @cheeseng @milessabin @adriaanm I've published 2.12.0-RC2 builds for ScalaCheck 1.11.6, 1.12.5 and 1.13.2 now.

Sorry for the delay this time.

**Pull request merged**
